name: Push - build and deploy App
on:
  push:
    branches:
      - master
      - staging
      - development
    paths:
      - 'src/**'
      - '.github/workflows/deploy-to-vercel.yaml'
      - 'yarn.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: package.json
      - run: yarn install
      - run: yarn lint
      - run: yarn build
