name: Pull Request - build and test App
on:
  pull_request:
    branches: [main, staging, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: package.json
      - run: npm install
      - run: npm run lint
      - run: npm run build